# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import datetime
import mysite.apps.historias.models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consecutivo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('numero', models.PositiveIntegerField(default=mysite.apps.historias.models.number, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='historia_clinica',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('primera_vez', models.BooleanField(default=False)),
                ('hijos', models.CharField(default=b'N', max_length=2, verbose_name='Hijos', choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('num_hijos', models.CharField(default=b'0', max_length=2, null=True, verbose_name='N\xba Hijos', blank=True)),
                ('turno', models.CharField(default=b'D', max_length=1, verbose_name='Turno', choices=[(b'D', b'Diurno'), (b'N', b'Nocturno'), (b'R', b'Rotatorio')])),
                ('actividad', models.CharField(default=b'P', max_length=1, verbose_name='Actividad Realizada', choices=[(b'P', b'De Pie'), (b'S', b'Sentado'), (b'D', b'Deambulado')])),
                ('a_empresa1', models.CharField(max_length=100, null=True, blank=True)),
                ('a_ocupacion1', models.CharField(max_length=100, null=True, blank=True)),
                ('a_tiempo1', models.CharField(max_length=50, null=True, blank=True)),
                ('a_biolog1', models.CharField(default=b'6', max_length=1, choices=[(b'1', b'Virus'), (b'2', b'Bacteria'), (b'3', b'Hongos'), (b'4', b'Parasitos'), (b'5', b'Otros'), (b'6', b'Ninguno')])),
                ('a_mec1', models.CharField(default=b'5', max_length=1, choices=[(b'1', b'Ca\xc3\xaddas'), (b'2', b'Contusiones'), (b'3', b'Torceduras'), (b'4', b'Otros'), (b'5', b'Ninguno')])),
                ('a_fis1', models.CharField(default=b'B', max_length=1, choices=[(b'1', b'Quemaduras por Electricidad 1er grado'), (b'2', b'Quemaduras por Electricidad  2do grado'), (b'3', b'Quemaduras por Electricidad  3er grado'), (b'4', b'Altas temperaturas'), (b'5', b'Bajas temperaturas'), (b'6', b'Iluminaci\xc3\xb3n'), (b'7', b'Radiaciones'), (b'8', b'Vibraciones'), (b'9', b'Ruido'), (b'A', b'Otros'), (b'B', b'Ninguno')])),
                ('a_erg1', models.CharField(default=b'4', max_length=1, choices=[(b'1', b'Posturas'), (b'2', b'Reubicaci\xc3\xb3n de Puesto'), (b'3', b'Otros'), (b'4', b'Ninguno')])),
                ('a_psi1', models.CharField(default=b'4', max_length=1, choices=[(b'1', b'Estr\xc3\xa9s laboral'), (b'2', b'Acoso laboral'), (b'3', b'Otros'), (b'4', b'Ninguno')])),
                ('a_qui1', models.CharField(default=b'F', max_length=1, choices=[(b'1', b'Vapores'), (b'2', b'Gases'), (b'3', b'Quemaduras por corrosivo 1 2 y 3 grado'), (b'4', b'Inflamables'), (b'5', b'Toxicos'), (b'6', b'Irritantes'), (b'7', b'Muy toxicos'), (b'8', b'Explosivos'), (b'9', b'Radiactivos'), (b'A', b'Nocivos'), (b'B', b'Explosivos'), (b'C', b'Polvos'), (b'D', b'Solidos'), (b'E', b'Otros'), (b'F', b'Ninguno')])),
                ('a_prot1', models.CharField(default=b'S', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('a_empresa2', models.CharField(max_length=100, null=True, blank=True)),
                ('a_ocupacion2', models.CharField(max_length=100, null=True, blank=True)),
                ('a_tiempo2', models.CharField(max_length=50, null=True, blank=True)),
                ('a_biolog2', models.CharField(default=b'6', max_length=1, choices=[(b'1', b'Virus'), (b'2', b'Bacteria'), (b'3', b'Hongos'), (b'4', b'Parasitos'), (b'5', b'Otros'), (b'6', b'Ninguno')])),
                ('a_mec2', models.CharField(default=b'5', max_length=1, choices=[(b'1', b'Ca\xc3\xaddas'), (b'2', b'Contusiones'), (b'3', b'Torceduras'), (b'4', b'Otros'), (b'5', b'Ninguno')])),
                ('a_fis2', models.CharField(default=b'B', max_length=1, choices=[(b'1', b'Quemaduras por Electricidad 1er grado'), (b'2', b'Quemaduras por Electricidad  2do grado'), (b'3', b'Quemaduras por Electricidad  3er grado'), (b'4', b'Altas temperaturas'), (b'5', b'Bajas temperaturas'), (b'6', b'Iluminaci\xc3\xb3n'), (b'7', b'Radiaciones'), (b'8', b'Vibraciones'), (b'9', b'Ruido'), (b'A', b'Otros'), (b'B', b'Ninguno')])),
                ('a_erg2', models.CharField(default=b'4', max_length=1, choices=[(b'1', b'Posturas'), (b'2', b'Reubicaci\xc3\xb3n de Puesto'), (b'3', b'Otros'), (b'4', b'Ninguno')])),
                ('a_psi2', models.CharField(default=b'4', max_length=1, choices=[(b'1', b'Estr\xc3\xa9s laboral'), (b'2', b'Acoso laboral'), (b'3', b'Otros'), (b'4', b'Ninguno')])),
                ('a_qui2', models.CharField(default=b'F', max_length=1, choices=[(b'1', b'Vapores'), (b'2', b'Gases'), (b'3', b'Quemaduras por corrosivo 1 2 y 3 grado'), (b'4', b'Inflamables'), (b'5', b'Toxicos'), (b'6', b'Irritantes'), (b'7', b'Muy toxicos'), (b'8', b'Explosivos'), (b'9', b'Radiactivos'), (b'A', b'Nocivos'), (b'B', b'Explosivos'), (b'C', b'Polvos'), (b'D', b'Solidos'), (b'E', b'Otros'), (b'F', b'Ninguno')])),
                ('a_prot2', models.CharField(default=b'S', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('accidente', models.CharField(default=b'N', max_length=2, verbose_name='Accidente de Trabajo', choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('enfermedad_profesional', models.CharField(default=b'N', max_length=2, verbose_name='Enfermedad Profesional', choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('detalle', models.TextField(max_length=200, null=True, blank=True)),
                ('quirurgicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('hospitalizacion', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('accidente_p', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('fracturas', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('tabaquismo', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('intoxicaciones', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('alcoholismo', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('mentales', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('asma', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('tbc', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('alergias', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('gripas', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('enf_piel', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('otologicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('diabetes', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('hematologicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('epilepsia', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('cancer', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('hipertension', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('otros', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_quirurgicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_hospitalizacion', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_accidente_p', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_fracturas', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_tabaquismo', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_intoxicaciones', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_alcoholismo', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_mentales', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_asma', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_tbc', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_alergias', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_gripas', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_enf_piel', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_otologicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_diabetes', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_hematologicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_epilepsia', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_cancer', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_hipertension', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('f_otros', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('descripcion_antecedente', models.TextField(max_length=300, null=True, blank=True)),
                ('alcohol', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('deportes', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('frecuencia', models.TextField(max_length=30, null=True, blank=True)),
                ('menarquia', models.CharField(max_length=50, null=True, blank=True)),
                ('hijos_vivos', models.CharField(default=b'0', max_length=2, null=True, verbose_name='N\xba Hijos Vivos', blank=True)),
                ('ciclos', models.CharField(max_length=50, null=True, blank=True)),
                ('gravida', models.CharField(max_length=6, null=True, blank=True)),
                ('partos', models.CharField(max_length=6, null=True, blank=True)),
                ('abortos', models.CharField(max_length=6, null=True, blank=True)),
                ('cesareas', models.CharField(max_length=6, null=True, blank=True)),
                ('fum', models.DateField(null=True, verbose_name=b'FUM', blank=True)),
                ('fup', models.DateField(null=True, verbose_name=b'FUP', blank=True)),
                ('dismenorrea', models.CharField(max_length=50, null=True, blank=True)),
                ('metrorragias', models.CharField(max_length=50, null=True, blank=True)),
                ('trastorno_ciclo', models.CharField(max_length=50, null=True, blank=True)),
                ('citologias', models.CharField(max_length=50, null=True, blank=True)),
                ('transtorno_otros', models.CharField(max_length=60, null=True, blank=True)),
                ('planificacion', models.CharField(default=b'9', max_length=1, choices=[(b'1', b'Preservativo'), (b'2', b'Implante Subdermico'), (b'3', b'DIU'), (b'4', b'Pomeroy'), (b'5', b'Inyecci\xc3\xb3n'), (b'6', b'P\xc3\xadldora'), (b'7', b'Ritmo'), (b'8', b'Otros'), (b'9', b'Ninguno')])),
                ('sintomas', models.TextField(max_length=200)),
                ('peso', models.CharField(max_length=4)),
                ('talla', models.CharField(max_length=6)),
                ('pulso', models.CharField(max_length=4)),
                ('temperatura', models.CharField(max_length=6)),
                ('presion_arterial', models.CharField(max_length=7)),
                ('masa_corporal', models.CharField(max_length=6)),
                ('estado', models.CharField(default=b'B', max_length=1, choices=[(b'B', b'Bueno'), (b'R', b'Regular'), (b'M', b'Malo')])),
                ('escribe', models.CharField(default=b'D', max_length=1, choices=[(b'Z', b'Zurdo'), (b'D', b'Diestro'), (b'A', b'Ambidiestro')])),
                ('cabeza', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('cuello', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('torax', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('abdomen', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('columna_cervical', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('columna_dorsal', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('columna_lumbo', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('m_superiores', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('m_inferiores', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('descripcion_osteomuscular', models.TextField(max_length=200, null=True, blank=True)),
                ('d_cuello', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('d_hombros', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('d_codo', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('d_muneca', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('d_cadera', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('d_rodilla', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('d_tobillo', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('d_cuello_o', models.TextField(default=b'Ninguna', max_length=50, null=True, blank=True)),
                ('d_hombros_o', models.TextField(default=b'Ninguna', max_length=50, null=True, blank=True)),
                ('d_codo_o', models.TextField(default=b'Ninguna', max_length=50, null=True, blank=True)),
                ('d_muneca_o', models.TextField(default=b'Ninguna', max_length=50, null=True, blank=True)),
                ('d_cadera_o', models.TextField(default=b'Ninguna', max_length=50, null=True, blank=True)),
                ('d_rodilla_o', models.TextField(default=b'Ninguna', max_length=50, null=True, blank=True)),
                ('d_tobillo_o', models.TextField(default=b'Ninguna', max_length=50, null=True, blank=True)),
                ('cicatrices', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('piel', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('craneo', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('conjuntivas', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('pupilas', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('anexos', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('reflejos', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('fondo', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('pabellones', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('ostocopia', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('tabique', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('cornetes', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('labios', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('faringe', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('tiroides', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('o_torax', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('pulmones', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('corazon', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('pared', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('viseras', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('hernias', models.CharField(default=b'N', max_length=1, choices=[(b'1', b'Inguinal Derecha'), (b'2', b'Inguinal Izquierda'), (b'3', b'Umbilical'), (b'4', b'Diafragmatica'), (b'5', b'Hiatal'), (b'N', b'Ninguno')])),
                ('genitales', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'No Explorado'), (b'E', b'Explorado')])),
                ('vascular', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('o_reflejos', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('marcha', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('coordinacion', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('ruidos', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normal'), (b'A', b'Anormal')])),
                ('extrasistoles', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('fibrilacion', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('soplos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('sistolicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('diastolicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('presistolicos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('vasos', models.CharField(default=b'N', max_length=1, choices=[(b'N', b'Normales'), (b'E', b'Escleroticos')])),
                ('varices', models.CharField(default=b'N', max_length=1, choices=[(b'P', b'Primero'), (b'S', b'Segundo'), (b'T', b'Tercero'), (b'N', b'Ninguno')])),
                ('observaciones', models.TextField(default=b'Ninguna', max_length=200, null=True, blank=True)),
                ('tunel', models.TextField(default=b'Ninguno', max_length=200, null=True, blank=True)),
                ('phannel', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('tinnel', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('pre_concepto', models.CharField(default=b'N', max_length=1, choices=[(b'A', b'Paciente Aparentemente Sano'), (b'O', b'Paciente con Observaciones'), (b'N', b'Ninguno')])),
                ('f_imagen', models.DateField(null=True, verbose_name=b'Fecha Imagenologia', blank=True)),
                ('r_imagen', models.TextField(max_length=150, null=True, blank=True)),
                ('f_audiometria', models.DateField(null=True, verbose_name=b'Fecha Audiometria', blank=True)),
                ('r_audiometria', models.TextField(max_length=150, null=True, blank=True)),
                ('f_visiometria', models.DateField(null=True, verbose_name=b'Fecha Visiometria', blank=True)),
                ('r_visiometria', models.TextField(max_length=150, null=True, blank=True)),
                ('f_espirometria', models.DateField(null=True, verbose_name=b'Fecha Espirometria', blank=True)),
                ('r_espirometria', models.TextField(max_length=150, null=True, blank=True)),
                ('f_laboratorio', models.DateField(null=True, verbose_name=b'Fecha Laboratorio', blank=True)),
                ('r_laboratorio', models.TextField(max_length=150, null=True, blank=True)),
                ('concepto', models.CharField(default=b'8', max_length=1, choices=[(b'1', b'Apto'), (b'2', b'Apto para trabajar en altura'), (b'3', b'Apto para manipulacion de alimentos'), (b'4', b'Apto con recomendaciones de seguimiento'), (b'5', b'Apto con patologia que no interfieren con el cargo'), (b'6', b'Apto con restricciones'), (b'7', b'Aplazado'), (b'8', b'Concepto NO emitido')])),
                ('remitir', models.CharField(default=b'N', max_length=1, choices=[(b'E', b'E.P.S'), (b'A', b'A.R.S'), (b'N', b'Ninguno')])),
                ('valoracion', models.TextField(max_length=80, null=True, blank=True)),
                ('recomendacion', models.TextField(max_length=500, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='historia_procedimientos',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hallazgos', models.TextField(max_length=1000)),
                ('impresion', models.TextField(default=b'', max_length=300)),
                ('remision', models.TextField(default=b'', max_length=300, null=True, blank=True)),
                ('ambito', models.CharField(default=b'1', max_length=1, verbose_name='Ambito de realizaci\xf3n del procedimiento', choices=[(b'1', b'Ambulatorio'), (b'2', b'Hospitalario'), (b'3', b'En urgencias')])),
                ('finalidad', models.CharField(default=b'1', max_length=1, verbose_name='Finalidad del procedimiento', choices=[(b'1', b'Diagnostico'), (b'2', b'Terapeutico'), (b'3', b'Proteccion especifica'), (b'4', b'Deteccion temprana de enfermedad general'), (b'5', b'Deteccion temprana de enfermedad profesional')])),
                ('personal', models.CharField(default=b'1', max_length=1, verbose_name='Personal que atiende', choices=[(b'1', b'M\xc3\xa9dico (a) especialista'), (b'2', b'M\xc3\xa9dico (a) general'), (b'3', b'Enfermera (o)'), (b'4', b'Auxiliar de enfermer\xc3\xada'), (b'5', b'Otro')])),
                ('forma', models.CharField(default=b'1', max_length=1, verbose_name='Forma de realizacion del acto quirurgico', choices=[(b'1', b'\xc3\x9anico o unilateral'), (b'2', b'Multiple o Bilateral misma via, diferente especialidad'), (b'3', b'Multiple o Bilateral misma via, igual especialidad'), (b'4', b'Multiple o Bilateral diferente via, diferente especialidad'), (b'5', b'Multiple o Bilateral diferente via, igual especialidad')])),
            ],
        ),
        migrations.CreateModel(
            name='laboratorios',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('examen', models.CharField(max_length=50)),
                ('fecha', models.DateField(null=True, verbose_name=b'Fecha Examen', blank=True)),
                ('resultado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Fecha Orden')),
                ('fecha_atencion', models.DateField(default=datetime.date.today, verbose_name=b'Fecha Atencion')),
                ('status', models.CharField(default=b'P', max_length=1, verbose_name=b'Estado', choices=[(b'P', b'Pendiente'), (b'R', b'Realizada')])),
                ('examen', models.CharField(default=b'5', max_length=2, verbose_name='Examen de', choices=[(b'1', b'Ingreso'), (b'2', b'Periodico'), (b'3', b'Egreso'), (b'4', b'Otros'), (b'5', b'Ninguno')])),
                ('examen_adicional', models.CharField(default=b'3', max_length=2, verbose_name='Examen Adicional', choices=[(b'1', b'Examen de Altura'), (b'2', b'Post Incapacidad'), (b'3', b'Ninguno'), (b'4', b'Manipulacion de Alimentos')])),
                ('empresa_cliente', models.CharField(max_length=200, verbose_name=b'Empresa Cliente')),
                ('cargo', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=100)),
                ('anulada', models.BooleanField(default=False)),
                ('razon_anulacion', models.TextField(max_length=100, null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ordenesProducto',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('orden', models.ForeignKey(related_name='OrdenProducto_orden', verbose_name='Orden', to='historias.orden')),
            ],
        ),
        migrations.CreateModel(
            name='posologias',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('medicamento', models.CharField(max_length=150)),
                ('uso', models.TextField(max_length=300)),
                ('orden', models.ForeignKey(related_name='posologias_orden', to='historias.orden')),
            ],
        ),
        migrations.CreateModel(
            name='remision',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('ordenado', models.CharField(max_length=150)),
                ('descripcion_orden', models.TextField(max_length=300)),
                ('entidad', models.CharField(max_length=100)),
                ('orden', models.ForeignKey(related_name='remision_orden', to='historias.orden')),
            ],
        ),
        migrations.CreateModel(
            name='remisionlab',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('laboratorio', models.CharField(max_length=150)),
                ('orden', models.ForeignKey(related_name='remisionlab_orden', to='historias.orden')),
            ],
        ),
        migrations.CreateModel(
            name='test_altura',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('convulsiones_p', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('diabetes', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('reacciones', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('claustrofobia', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('acrofobia', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('vertigos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('epilepsia', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('enfermedad_mental', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('a_cardiaco', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('a_cerebro_v', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('angina_pecho', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('insuficiencia_cardiaca', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('hinchazon_pies', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('latidos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('presion', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('otro', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dolor_pecho1', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dolor_pecho2', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dolor_pecho3', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('late_irregularmente', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dolor_pecho_indigestion', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('otros_sintomas', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('lentes_contacto', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('lentes', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('daltonismo', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('problema_ojos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('ob_problema', models.CharField(max_length=150, null=True, blank=True)),
                ('prob_pulmonares', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('prob_circulacion', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('presion_alta', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('convulsiones', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('enf_mental', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('perdida_vista', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dano_oidos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dificultad_oir', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('aparato_oir', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('prob_audicion', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('d_prob_audicion', models.CharField(max_length=150, null=True, blank=True)),
                ('debilidad_brazos', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dolor_espalda', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dificultad_extremidades', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dolor_rigidez', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dif_cabeza_arriba', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dif_cabeza_lado', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dif_agacharse', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dif_agacharse_piso', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('dif_escalera', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('lesion_espalda', models.CharField(default=b'N', max_length=1, choices=[(b'S', b'Si'), (b'N', b'No')])),
                ('d_lesion', models.CharField(max_length=150, null=True, blank=True)),
                ('romberg', models.CharField(default=b'N', max_length=1, choices=[(b'A', b'Anormal'), (b'N', b'Normal')])),
                ('ob_romberg', models.CharField(max_length=150, null=True, blank=True)),
                ('baranay', models.CharField(default=b'N', max_length=1, choices=[(b'A', b'Anormal'), (b'N', b'Normal')])),
                ('ob_baranay', models.CharField(max_length=150, null=True, blank=True)),
                ('hallpike', models.CharField(default=b'N', max_length=1, choices=[(b'A', b'Anormal'), (b'N', b'Normal')])),
                ('ob_hallpike', models.CharField(max_length=150, null=True, blank=True)),
                ('babinski_m_d', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_babinski_m_d', models.CharField(max_length=150, null=True, blank=True)),
                ('babinski_m_i', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_babinski_m_i', models.CharField(max_length=150, null=True, blank=True)),
                ('babinski_m_n', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_babinski_m_n', models.CharField(max_length=150, null=True, blank=True)),
                ('unterberger_m_d', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_unterberger_m_d', models.CharField(max_length=150, null=True, blank=True)),
                ('unterberger_m_c', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_unterberger_m_c', models.CharField(max_length=150, null=True, blank=True)),
                ('unterberger_m_i', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_unterberger_m_i', models.CharField(max_length=150, null=True, blank=True)),
                ('neg_vert_per', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_neg_vert_per', models.CharField(max_length=150, null=True, blank=True)),
                ('pos_vert_per', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_pos_vert_per', models.CharField(max_length=150, null=True, blank=True)),
                ('post_vert_cent', models.CharField(max_length=5, null=True, blank=True)),
                ('ob_post_vert_cent', models.CharField(max_length=150, null=True, blank=True)),
                ('orden', models.ForeignKey(related_name='test_altura_orden', to='historias.orden')),
            ],
        ),
    ]
